export enum NetworkEnum {
  ETH_MAINNET = "ETH_MAINNET",
  SEPOLIA = "SEPOLIA",
  POLYGON_MAINNET = "POLYGON_MAINNET",
  ARBITRUM_MAINNET = "ARBITRUM_MAINNET",
  OPTIMISM_MAINNET = "OPTIMISM_MAINNET",
}
